### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by xAxee** [xNorbig/xnorbig.github.io#1]
Pod wymaganymi przedmiotami zrób jakieś podsumowanie.

Zrób, aby przedmioty były jakoś posegregowane tzn. cobble pod cobblem stone pod stonem, ale tylko do tych 'pospolitych' takie jak np. luk / szlam do jednej lubryki.

**Comment by xNorbig** [comment]
Ale takie podsumowanie istnieje przecież. A co do sortowania nie widzę sensu
